CCARGS	+= -m32 -fno-PIC -fno-PIE
LDARGS	+= --script=$(TOPSRC)/sys/i386/link.ld -melf_i386
SRCS 	+= $(TOPSRC)/sys/i386/archentry.c $(TOPSRC)/sys/i386/devcons.c $(TOPSRC)/sys/i386/bootbump.c \
			$(TOPSRC)/sys/i386/bootpt.c
SSRCS	+= $(TOPSRC)/sys/i386/boot.S
